name: 'Netlify'
on:
    schedule:
        # - cron:  '0 14 * * *'
        - cron '* * * * *',
jobs:
    deploy:
        name: 'Deploy'
        runs-on: ubuntu-latest
        steps:
              - uses: actions/checkout@v1
              - uses: jsmrcaga/action-netlify-deploy@main
              with:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_DEPLOY_TO_PROD: true
